### ISSUE TITLE
Symlink issues with Docker

### ISSUE THREAD

**Issue by startupengine** [hendrikmaus/drafter-installer#4]
Docker doesn't play well with symlinks -- I assume that is why this installer fails when run within a Docker container. Is there a workaround for installing Drafter that doesn't involve the use of symlinks?

**Comment by hendrikmaus** [comment]
I will try to reproduce an issue with installing inside a docker container and commit the outcome to the repository.

**Comment by hendrikmaus** [comment]
I was not able to reproduce any issues with the symlink inside of a linux container. I added a Dockerfile and some documentation https://github.com/hendrikmaus/drafter-installer/blob/master/test/Docker.md

Maybe you ran into the mountpoint trap, where the symlink is built fine within the container, but is not valid on the host system because the code was mounted to a different path while building? The scenario is laid out in the documentation document linked above.
